In [1]:
# Creating a test matrix:
a <- matrix(seq(1, 100), 25, 4)
a

[,1] [,2] [,3] [,4]
 [1,]  1   26   51    76 
 [2,]  2   27   52    77 
 [3,]  3   28   53    78 
 [4,]  4   29   54    79 
 [5,]  5   30   55    80 
 [6,]  6   31   56    81 
 [7,]  7   32   57    82 
 [8,]  8   33   58    83 
 [9,]  9   34   59    84 
[10,] 10   35   60    85 
[11,] 11   36   61    86 
[12,] 12   37   62    87 
[13,] 13   38   63    88 
[14,] 14   39   64    89 
[15,] 15   40   65    90 
[16,] 16   41   66    91 
[17,] 17   42   67    92 
[18,] 18   43   68    93 
[19,] 19   44   69    94 
[20,] 20   45   70    95 
[21,] 21   46   71    96 
[22,] 22   47   72    97 
[23,] 23   48   73    98 
[24,] 24   49   74    99 
[25,] 25   50   75   100

In [2]:
# Scalar multiplication
2 * a

[,1] [,2] [,3] [,4]
 [1,]  2    52  102  152 
 [2,]  4    54  104  154 
 [3,]  6    56  106  156 
 [4,]  8    58  108  158 
 [5,] 10    60  110  160 
 [6,] 12    62  112  162 
 [7,] 14    64  114  164 
 [8,] 16    66  116  166 
 [9,] 18    68  118  168 
[10,] 20    70  120  170 
[11,] 22    72  122  172 
[12,] 24    74  124  174 
[13,] 26    76  126  176 
[14,] 28    78  128  178 
[15,] 30    80  130  180 
[16,] 32    82  132  182 
[17,] 34    84  134  184 
[18,] 36    86  136  186 
[19,] 38    88  138  188 
[20,] 40    90  140  190 
[21,] 42    92  142  192 
[22,] 44    94  144  194 
[23,] 46    96  146  196 
[24,] 48    98  148  198 
[25,] 50   100  150  200

In [4]:
# transposing a matrix:
t(a)

[,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8] [,9] [,10] [,11] [,12] [,13] [,14]
[1,]  1    2    3    4    5    6    7    8    9   10    ...   16    17    18   
[2,] 26   27   28   29   30   31   32   33   34   35    ...   41    42    43   
[3,] 51   52   53   54   55   56   57   58   59   60    ...   66    67    68   
[4,] 76   77   78   79   80   81   82   83   84   85    ...   91    92    93   
     [,15] [,16] [,17] [,18] [,19] [,20] [,21]
[1,] 19    20    21    22    23    24     25  
[2,] 44    45    46    47    48    49     50  
[3,] 69    70    71    72    73    74     75  
[4,] 94    95    96    97    98    99    100

In [16]:
# Element-Wise Equivalence:
t(a) == matrix(seq(1, 100), 4, 25, byrow=TRUE)

[,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8] [,9] [,10] [,11] [,12] [,13] [,14]
[1,] TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE  ...   TRUE  TRUE  TRUE 
[2,] TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE  ...   TRUE  TRUE  TRUE 
[3,] TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE  ...   TRUE  TRUE  TRUE 
[4,] TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE  ...   TRUE  TRUE  TRUE 
     [,15] [,16] [,17] [,18] [,19] [,20] [,21]
[1,] TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE 
[2,] TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE 
[3,] TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE 
[4,] TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE

In [8]:
# Matrix multiplication:
mat_multed <- a %*% t(a) # Returns a 25 x 25 matrix
mat <- a %o% t(a)

In [11]:
ncol(mat)

[1] 4

In [17]:
matrix(mat, nrow(mat), ncol(mat))

[,1] [,2] [,3] [,4]
 [1,]  1   26   51    76 
 [2,]  2   27   52    77 
 [3,]  3   28   53    78 
 [4,]  4   29   54    79 
 [5,]  5   30   55    80 
 [6,]  6   31   56    81 
 [7,]  7   32   57    82 
 [8,]  8   33   58    83 
 [9,]  9   34   59    84 
[10,] 10   35   60    85 
[11,] 11   36   61    86 
[12,] 12   37   62    87 
[13,] 13   38   63    88 
[14,] 14   39   64    89 
[15,] 15   40   65    90 
[16,] 16   41   66    91 
[17,] 17   42   67    92 
[18,] 18   43   68    93 
[19,] 19   44   69    94 
[20,] 20   45   70    95 
[21,] 21   46   71    96 
[22,] 22   47   72    97 
[23,] 23   48   73    98 
[24,] 24   49   74    99 
[25,] 25   50   75   100

In [26]:
# Creating an identity matrix:
diag(3)

[,1] [,2] [,3]
[1,] 1    0    0   
[2,] 0    1    0   
[3,] 0    0    1

# Question 1:

In [18]:
x = matrix(seq(1, 100), 10, 10)

In [19]:
t(t(x)) == x

[,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8] [,9] [,10]
 [1,] TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE 
 [2,] TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE 
 [3,] TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE 
 [4,] TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE 
 [5,] TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE 
 [6,] TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE 
 [7,] TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE 
 [8,] TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE 
 [9,] TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE 
[10,] TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE

In [22]:
a <- x %*% matrix(1, ncol(x))
matrix(a, nrow(a), ncol(a))

[,1]
 [1,] 460 
 [2,] 470 
 [3,] 480 
 [4,] 490 
 [5,] 500 
 [6,] 510 
 [7,] 520 
 [8,] 530 
 [9,] 540 
[10,] 550

In [23]:
x * 1 == x

[,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8] [,9] [,10]
 [1,] TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE 
 [2,] TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE 
 [3,] TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE 
 [4,] TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE 
 [5,] TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE 
 [6,] TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE 
 [7,] TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE 
 [8,] TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE 
 [9,] TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE 
[10,] TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE

In [25]:
diag(ncol(x))

[,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8] [,9] [,10]
 [1,] 1    0    0    0    0    0    0    0    0    0    
 [2,] 0    1    0    0    0    0    0    0    0    0    
 [3,] 0    0    1    0    0    0    0    0    0    0    
 [4,] 0    0    0    1    0    0    0    0    0    0    
 [5,] 0    0    0    0    1    0    0    0    0    0    
 [6,] 0    0    0    0    0    1    0    0    0    0    
 [7,] 0    0    0    0    0    0    1    0    0    0    
 [8,] 0    0    0    0    0    0    0    1    0    0    
 [9,] 0    0    0    0    0    0    0    0    1    0    
[10,] 0    0    0    0    0    0    0    0    0    1

In [ ]:
# You can solve linear equations using the linear formula and the solve function.

# Question 2:

In [30]:
# Creating an matrix:
answer_mat <- cbind(c(10, 5, 7, 4))
coff_mat <- matrix(c(3, 4, -5, 1, 2, 2, 2, -1, 1, -1, 5, -5, 5, 0, 0, 1), 4, 4, byrow=TRUE)

In [31]:
answer_mat

[,1]
[1,] 10  
[2,]  5  
[3,]  7  
[4,]  4

In [32]:
coff_mat

[,1] [,2] [,3] [,4]
[1,] 3     4   -5    1  
[2,] 2     2    2   -1  
[3,] 1    -1    5   -5  
[4,] 5     0    0    1

In [37]:
parameter <- solve(coff_mat, answer_mat)

In [38]:
coff_mat %*% parameter

[,1]
[1,] 10  
[2,]  5  
[3,]  7  
[4,]  4

In [39]:
parameter

[,1]      
[1,]  1.2477876
[2,]  1.0176991
[3,] -0.8849558
[4,] -2.2389381

# Question 3:

In [40]:
a <- matrix(1:12, nrow=4)
b <- matrix(1:15, nrow=3)
a

[,1] [,2] [,3]
[1,] 1    5     9  
[2,] 2    6    10  
[3,] 3    7    11  
[4,] 4    8    12

In [41]:
b

[,1] [,2] [,3] [,4] [,5]
[1,] 1    4    7    10   13  
[2,] 2    5    8    11   14  
[3,] 3    6    9    12   15

In [43]:
answer <- a %*% b

In [44]:
answer[3, 2]

[1] 113

In [49]:
dot <- function(mat1, mat2){
    mat3 <- mat1 * mat2
    answer <- 0
    for (i in mat3){
        answer <- answer + i
    }
    print(answer)
}

In [51]:
dot(a[3,], t(b[, 2]))

[1] 113
