In [1]:
library(UsingR)

Loading required package: MASS

Loading required package: HistData

Loading required package: Hmisc


Attaching package: 'Hmisc'


The following objects are masked from 'package:base':

    format.pval, units




In [2]:
# Creating a vector:
vector1 <- c(1, 5, 3, 4) # Similar to list in python and support dynamic types.

In [3]:
vector1

[1] 1 5 3 4

In [4]:
# Converting a vector to a column matrix:
cbind(vector1)

vector1
[1,] 1      
[2,] 5      
[3,] 3      
[4,] 4

In [5]:
# Converting to a row matrix:
rbind(vector1)

[,1] [,2] [,3] [,4]
vector1 1    5    3    4

In [6]:
# Converting to a specified matrix:
matrix(vector1, 2, 2)

[,1] [,2]
[1,] 1    3   
[2,] 5    4

The arguments to a matrix is matrix(data, rows, columns).

The main difference between an R matrix and dataframe is that the dataframe supports multiple value types.

In [7]:
# Several function results that return a convertable vector:
matrix(rnorm(10), 2, 5)

[,1]       [,2]       [,3]     [,4]       [,5]      
[1,] -0.2221972 -0.2621368 1.495672 -0.1036073  0.5417071
[2,]  1.8207345  0.2031187 1.276952 -0.5008801 -0.5515232

In [18]:
# Can also create by row:
matrix(1:10, 2, 5, byrow=TRUE)

[,1] [,2] [,3] [,4] [,5]
[1,] 1    2    3    4     5  
[2,] 6    7    8    9    10

In [26]:
# Lastly, the actual range function with step:
seq(2, 10, 2)

[1]  2  4  6  8 10

## Question 1:

In [8]:
# Creating a matrix like the range function in python:
matrix(1:1000, 100, 10)[25, 3] # Indexing like a vector.

[1] 225

#  Question 2:

In [9]:
# Creating a 10 x 5 matrix:
vector1 <- 1:10
matrix1 <- cbind(vector1, vector1 * 2, vector1 * 3, vector1 * 4, vector1 * 5)

In [13]:
sum(matrix1[7,])

[1] 105

# Question 3:

In [15]:
matrix(1:60,20,3) # Just reshapes 1 to 60 in 20 x 3 matrix.

[,1] [,2] [,3]
 [1,]  1   21   41  
 [2,]  2   22   42  
 [3,]  3   23   43  
 [4,]  4   24   44  
 [5,]  5   25   45  
 [6,]  6   26   46  
 [7,]  7   27   47  
 [8,]  8   28   48  
 [9,]  9   29   49  
[10,] 10   30   50  
[11,] 11   31   51  
[12,] 12   32   52  
[13,] 13   33   53  
[14,] 14   34   54  
[15,] 15   35   55  
[16,] 16   36   56  
[17,] 17   37   57  
[18,] 18   38   58  
[19,] 19   39   59  
[20,] 20   40   60

In [16]:
matrix(1:60,20,3,byrow=TRUE) # It creates by row.

[,1] [,2] [,3]
 [1,]  1    2    3  
 [2,]  4    5    6  
 [3,]  7    8    9  
 [4,] 10   11   12  
 [5,] 13   14   15  
 [6,] 16   17   18  
 [7,] 19   20   21  
 [8,] 22   23   24  
 [9,] 25   26   27  
[10,] 28   29   30  
[11,] 31   32   33  
[12,] 34   35   36  
[13,] 37   38   39  
[14,] 40   41   42  
[15,] 43   44   45  
[16,] 46   47   48  
[17,] 49   50   51  
[18,] 52   53   54  
[19,] 55   56   57  
[20,] 58   59   60

In [19]:
x=11:20;rbind(x,2*x,3*x) # Creates a byrow multiple of vector x

[,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8] [,9] [,10]
x 11   12   13   14   15   16   17   18   19   20   
  22   24   26   28   30   32   34   36   38   40   
  33   36   39   42   45   48   51   54   57   60

In [20]:
x=1:40;matrix(3*x,20,2) # Creating a matrix of 20 x 2

[,1] [,2]
 [1,]  3    63 
 [2,]  6    66 
 [3,]  9    69 
 [4,] 12    72 
 [5,] 15    75 
 [6,] 18    78 
 [7,] 21    81 
 [8,] 24    84 
 [9,] 27    87 
[10,] 30    90 
[11,] 33    93 
[12,] 36    96 
[13,] 39    99 
[14,] 42   102 
[15,] 45   105 
[16,] 48   108 
[17,] 51   111 
[18,] 54   114 
[19,] 57   117 
[20,] 60   120

# Question 5:

In [21]:
seq(10, 1, -2) # Returns a vector counting down by 2.

[1] 10  8  6  4  2